### PR TITLE
Use different source for Archlinux

### LINKED ISSUE #5: Update Arch Linux data source to reproducible.archlinux.org
While checking the status of [kitty](https://ismypackagereproducibleyet.org/?pkg=kitty&query=query) I noticed it's listed as "fails to build from source" on Arch Linux because the status is pulled from `tests.reproducible-builds.org`. There's some known issues with this one and it's generally recommended to use `reproducible.archlinux.org`, since this data is for rebuild attempts of the actual binary packages distributed to users.

Json data can be fetched from here:

```
https://reproducible.archlinux.org/api/v0/pkgs/list
```

Thanks!

### PR DESCRIPTION
**Pull request by bmwiedemann**
FIXME: Needs proper URL to point to learn more

fixes #5

There's some known issues with tests.reproducible-builds.org

### CODE REVIEW

File: json2db.pl [hunk 1]
```diff
@@ -14,10 +14,15 @@
 
 foreach my $pkg (@$pkgs) {
     #print $pkg->{package}," ", $pkg->{status},"\n";
-    $pkg->{status} =~ s/unreproducible/FTBR/;
+    my $status = $pkg->{status};
+    $status =~ s/unreproducible/FTBR/;
+    $status =~ s/BAD/FTBR/;
+    $status =~ s/UNKWN/FTBFS/;
+    $status =~ s/GOOD/reproducible/;
```
Comment (kpcyrd) [inline json2db.pl]: Overall it looks fine:

- `unreproducible` does not exist as status in rebuilderd
- `BAD` can mean either `FTBR` or `FTBFS`, the difference is currently not tracked (everything that isn't `GOOD`)
- `UNKWN` is the "pending" status, waiting to be picked up by a worker

Comment (bmwiedemann) [reply json2db.pl]: `unreproducible` is for mapping the openSUSE format to Debian format. You can ignore that here.

For `UNKWN` - would it be possible to get an export with the last known state?

I'd then map `BAD` to `FTBR` - because if it does not build, it also does not build reproducibly.

Comment (kpcyrd) [reply json2db.pl]: > For UNKWN - would it be possible to get an export with the last known state?

With the current implementation the previous status is not available unfortunately. If a package version disappears from the package database (core.db, extra.db) it also gets removed from the rebuilderd database.

**Comment by kpcyrd** [comment]
I had an idea in the meantime on how to tell FTBFS and FTBR apart:

- `.status == BAD && .has_diffoscope == false` - Failed to build from source
- `.status == BAD && .has_diffoscope == true` - Successfully built a package, but doesn't match what Arch Linux distributes (FTBR)

**Comment by bmwiedemann** [comment]
I implemented this now with commit 1250e4a2448831f9e74354ecb186a3caf8c24f5a
